article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name ="article"

urlpatterns = [
    path('dashboard/',views.dashboard,name="dashboard"),
    path('addarticle/',views.addArticle,name="addarticle"),
    path('article/<int:id>',views.detail,name="detail"),
    path('update/<int:id>',views.updateArticle,name="update"),
    path('delete/<int:id>',views.deleteArticle,name="delete"),
    path('',views.articles,name="articles"),
    path('comment/<int:id>',views.addComment,name="comment"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


from article import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name="index"),
    path('about/', views.about,name="about"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),
    
]

urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="user"
urlpatterns = [
    path('register/',views.register,name="register"),
    path('login/',views.loginUser,name="login"),
    path('logout/',views.logoutUser,name="logout"),
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE,verbose_name="Yazar")
    title = models.CharField(max_length=50,verbose_name="Başlık")
    content = RichTextField(verbose_name="İçerik")
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Oluşturma Tarihi")
    article_image = models.FileField(blank = True,null=True,verbose_name="Makaleye Resim Yüklenyin")
    def __str__(self):
        return self.title
    class Meta:
        ordering = ["-created_date"]

class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete= models.CASCADE,verbose_name="Makale",related_name="comments")
    comment_author = models.CharField(max_length = 50,verbose_name = "İsim", null=False, blank=False)
    comment_content = models.CharField(max_length=200,verbose_name="Yorum" )
    comment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment_content
    
    class Meta:
        ordering = ["-comment_date"]

user/models.py
from django.db import models

# Create your models here.

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","article_image"]

user/forms.py
from django import forms
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField(label="Kullanıcı Adı")
    password = forms.CharField(label="Parola",widget= forms.PasswordInput)




class RegisterForm(forms.Form):
    username = forms.CharField(max_length=50,label="Kullanıcı Adı")
    password = forms.CharField(max_length=20,label="Parola",widget=forms.PasswordInput)
    confirm = forms.CharField(max_length=20,label="Parola Doğrula",widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")


        if User.objects.filter(username__iexact=username).exists():
            raise forms.ValidationError('Bu kullanıcı adı kullanılıyor...')
        
        if password and confirm and password != confirm:
            raise forms.ValidationError("Parolalar eşleşmiyor")
        values ={
            "username": username,
            "password": password,
        }
        return values

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from django.contrib.auth.decorators import login_required
from .forms import ArticleForm
from django.contrib import messages
from .models import Article,Comment

# Create your views here.

def articles(request):
    keyword = request.GET.get("keyword")

    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles":articles})
    articles = Article.objects.all()

    return render(request,"articles.html",{"articles":articles})

def index(request):
    
    return render(request,"index.html")

def about(request):
    return render(request,"about.html")


@login_required(login_url="user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {
        "articles":articles
    }

    return render(request,"dashboard.html",context)

@login_required(login_url="user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request,"Makale Oluşturuldu.")
        return redirect("article:dashboard")

    return render(request,"addarticle.html",{"form":form})

def detail(request, id):
    #article = Article.objects.filter(id=id).first()
    #Debug=True oldugu için yani geliştirici modu aktif oldugu için hata gibi gözükyüor
    article = get_object_or_404(Article,id=id)

    comments = article.comments.all()


    if not article:
        return HttpResponse("Makale bulunamadı.")

    return render(request, "detail.html", {"article": article, "comments":comments})

@login_required(login_url="user:login")
def updateArticle(request,id):
    article = get_object_or_404(Article,id=id)
    form = ArticleForm(request.POST or None, request.FILES or None,instance=article)
    if form.is_valid():
        article = form.save(commit=False)
        article.author=request.user
        article.save()
        messages.success(request,"Makale Güncellendi")
        return redirect("article:dashboard")
    
    return render(request,"update.html",{"form":form})

@login_required(login_url="user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article,id=id)
    article.delete()
    messages.success(request,"Makale silindi")

    return redirect("article:dashboard")

# Yorum Ekleme
def addComment(request,id):
    article= get_object_or_404(Article,id=id)

    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author = comment_author, comment_content = comment_content)

        newComment.article = article
        newComment.save()

    return redirect(reverse("article:detail",kwargs={"id":id}))

user/views.py
from django.shortcuts import render,redirect
from .forms import RegisterForm,LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import login,logout,authenticate
from django.contrib import messages
# Create your views here.



def register(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        newUser =User(username=username)
        newUser.set_password(password)
            
        newUser.save()
        login(request,newUser)
        messages.info(request,"Kayıt Başarılı....")
        return redirect("index")
    
    context = {
            "form": form
        }
    return render(request,"register.html",context)
    
    
    """
    if request.method =="POST":
        form = RegisterForm(request.POST)
        


    else:
        form = RegisterForm()
        context = {
            "form": form
        }
        return render(request,"register.html",context)
    
    form = RegisterForm()
    context = {
        "form": form
    }
    return render(request,"register.html",context)
"""
def loginUser(request):
    form = LoginForm(request.POST or None)

    context={
        "form":form

    }
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user= authenticate(username = username, password = password)
        if user is None:
            messages.info(request,"Kullanıcı Adı veya Parola Hatalı")
            return render(request,"login.html",context)
        messages.success(request,"Giriş Başarılı")
        login(request,user)
        return redirect("index")

    return render(request,"login.html",context)

def logoutUser(request):
    logout(request)
    messages.success(request,"Çıkış Başarılı")
    return redirect("index")

templates/about.html
{% extends "layout.html" %}

{% block body %}
<h3>Hakkımda</h3>
<hr>
<p>İzmit'te ikamet eden bir bilgisayar programlama mezunu olarak, Bilgisayar Programlama alanındaki tutkumu ve sürekli öğrenme isteğimi benimsemekteyim. Eğitim hayatımı Balıkesir Gönen Üniversitesi'nde aldığım bilgisayar programlama eğitimiyle şekillendirdim. Bu eğitim süreci, teknik becerilerimi geliştirmek ve yazılım temel prensiplerini öğrenmek için güçlü bir temel oluşturdu.
Şu an, kariyerimdeki geleceği şekillendirmek amacıyla Udemy, BTK, Patika ve benzeri eğitim platformlarından alınan eğitimlere odaklanıyorum.
Özellikle back-end web geliştirme ve oyun geliştirme konularına yoğunlaşmış durumdayım.
</p>
<hr>
{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">

        <h3>Makale Oluştur</h3>
        <hr>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{ form|crispy }}
            <br>
            <button type="submit" class="btn btn-danger">Makale Oluştur</button>
        </form>

    </div>
  </div>


{% endblock body %}

templates/articles.html
{% extends "layout.html" %}

{% block body %}

<div class="row">
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
            <h3 style="float:left;">Makaleler</h3>
            <form style="float:right;">
                {% csrf_token %}
                <input type="text" name="keyword" class="input-sm" maxlength="64" placeholder="Ara...">
                <button type="submit" class="btn btn-danger ">Ara</button>
            </form>
            <br>
            <hr>
        </div>
    </div>
</div>

{% if articles %}
{% for article in articles %}

<div class="row">
    <div class="col-md-10 offset-md-3">
    <div class="col-lg-8">
        <!-- Post content-->
        <article>
            <!-- Post header-->
            <header class="mb-4">
                <!-- Post title-->
                <a href="{% url 'article:detail' article.id %}"> <h2 class="fw-bolder mb-1">{{article.title}}</h2> </a>
                <!-- Author -->
                <p class="lead">
                    {{article.author.username}} Tarafından Oluşturuldu.
                </p>
                <hr>
                <!-- Post meta content-->
                <div class="text-muted fst-italic mb-2">{{article.created_date}}</div>
                <hr>
            </header>
            <!-- Preview image figure-->
            {% if article.article_image %}
            <a href="/articles/article/{{article.id}}">
                <figure class="mb-4"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt="..." /></figure>
            </a>
            {% endif %}
            
            
            <!-- Post content-->
            <section class="mb-5">
                <p>{{article.content|safe|truncatewords:30}}</p>
            </section>
            <a style="float : right;" href="/articles/article/{{article.id}}" class="btn btn-danger">Devamını Oku</a>
            <hr>
            
        </article>
    </div>
</div>
</div>

{% endfor %}

{% else %}
<div class="alert alert-danger">
    Makale bulunmuyor
</div>
{% endif %}

{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}
<h3>Kontrol Paneli</h3>
<hr>
<p>
    Hoşgeldiniz, <smal>{{request.user.username}}</smal>
</p>
<hr>
<a class="btn btn-danger" href="{% url 'article:addarticle' %}">Makale Ekle</a>
<hr>
{% if articles %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">Başlık</th>
        <th scope="col">Yazar</th>
        <th scope="col">Tarih</th>
        <th scope="col">Güncelle</th>
        <th scope="col">Sil</th>
      </tr>
    </thead>
    <tbody>
        {% for article in articles %}
    <tr>
        <th scope="row">{{article.id}}</th>
        <td><a href="/articles/article/{{article.id}}">{{article.title}}</a></td>
        <td>{{article.author.username}}</td>
        <td>{{article.created_date}}</td>
        <td><a href="{% url 'article:update' article.id %}" class="btn btn-danger">Güncelle</a ></td>
        <td><a href="{% url 'article:delete' article.id %}" class="btn btn-danger">Sil</a ></td>
    </tr>
        {% endfor %}

     
    </tbody>
  </table>

{% else %}
<div class="alert alert-danger">Makale Yok

</div>
{% endif %}



{% endblock body %}

templates/detail.html
{% extends "layout.html" %}
{% block body %}

<div class="row">
    <div class="col-lg-8">
        <!-- Post content-->
        <article>
            <!-- Post header-->
            <header class="mb-4">
                <!-- Post title-->
                <h2 class="fw-bolder mb-1">{{article.title}}</h2>
                <!-- Author -->
                <p class="lead">
                    by {{article.author.username}}
                </p>
                <hr>
                
                <!-- Post meta content-->
                <div class="text-muted fst-italic mb-2">{{article.created_date}}</div>
                <hr>
                
            </header>
            <!-- Preview image figure-->
            {% if article.article_image %}
            <figure class="mb-4"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt="..." /></figure>
            
            {% endif %}
            
            
            <!-- Post content-->
            <section class="mb-5">
                <p>{{article.content|safe}}</p>
            </section>
            <hr>
            <h4>Yorumlar</h4>
            <hr>

            {% if comments %}
            {% for comment in comments %}
                <div class="media mb-4 ">
                    <div class="icon-container" 
                    style="    
                    width: 50px;
                    height: 50px;
                    overflow: hidden;
                    margin-right: 10px;"
                    >
                        <img class="d-flex mr-3 rounded-circle" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnIzLd2AEYnEMBJWAhnZH5Gg9txQdwWZLVxQ&usqp=CAU" alt="..." 
                        style="
                        width: 100%;
                        height: auto;
                        display: block;"
                        />
                    </div>
                    
                    <div class="mt-0">
                        <h3>{{comment.comment_author}}</h3>
                        <div style="display: flex; align-items: center;">
                            
                            {{comment.comment_content}}
                        </div>
                        
                        <span class="pipe" style="color: #999; font-size: 14px; ">{{comment.comment_date}}</span>
                    </div>
                    
                    
                </div>
            {% endfor %}
            {% else %}
            <div class="alert alert-danger">İlk Yorum yapan siz olun...</div>
            {% endif %}

            
        </article>
        <section class="mb-5" style="margin-top:10px;">
            <div class="card bg-light">
                <h5 class="card-header">Yorum Ekle</h5>
                <form method ="post" action ="{% url 'article:comment' article.id %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="formGroupExampleInput">İsim</label>
                        <input name ="comment_author"type="text" class="form-control" id="formGroupExampleInput" placeholder="İsim giriniz...">
                    </div>
                    <div class="form-group">
                        <label for="formGroupExampleInput"> Yorum</label>
                    <textarea name="comment_content" class="form-control" rows="3" placeholder="Yorum ekleyin..."></textarea>
                    </div>
                    
                    <!-- Comment form-->
                    <div class="mb-1 d-flex justify-content-end" >
                        <a button type="submit" class="btn btn-danger " href="{{request.META.HTTP_REFERER}}">Geri Dön</a>
                        <button type="submit" class="btn btn-danger ml-2">Ekle</button>
                    </div>
            </div>
                </form>
        </section>
    </div>
</div>





{% endblock body %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'index' %}">Apo Blog</a>

    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'about' %}">Hakkımızda</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'article:articles' %}">Makaleler</a>
          </li>
      </ul>

      <ul class="navbar-nav ml-auto">
      {% if request.user.is_authenticated %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'article:dashboard' %}">Kontrol Paneli</a>
      </li>

      <li class="nav-item active">
        <a class="nav-link" href="{% url 'user:logout' %}">Çıkış Yap</a>
      </li>
      {% else %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'user:login' %}">Giriş Yap</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'user:register' %}">Kayıt Olun</a>
      </li>
      {% endif %}       


      </ul>
    </div>
  </nav>

templates/includes/posttemplate.html
<div class="row">
    <div class="col-lg-8">
        <!-- Post content-->
        <article>
            <!-- Post header-->
            <header class="mb-4">
                <!-- Post title-->
                <h1 class="fw-bolder mb-1">Welcome to Blog Post!</h1>
                <!-- Post meta content-->
                <div class="text-muted fst-italic mb-2">Posted on January 1, 2023 by Start Bootstrap</div>
                <!-- Post categories-->
                <a class="badge bg-secondary text-decoration-none link-light" href="#!">Web Design</a>
                <a class="badge bg-secondary text-decoration-none link-light" href="#!">Freebies</a>
            </header>
            <!-- Preview image figure-->
            <figure class="mb-4"><img class="img-fluid rounded" src="https://dummyimage.com/900x400/ced4da/6c757d.jpg" alt="..." /></figure>
            <!-- Post content-->
            <section class="mb-5">
                <p class="fs-5 mb-4">Science is an enterprise that should be cherished as an activity of the free human mind. Because it transforms who we are, how we live, and it gives us an understanding of our place in the universe.</p>
                <p class="fs-5 mb-4">The universe is large and old, and the ingredients for life as we know it are everywhere, so there's no reason to think that Earth would be unique in that regard. Whether of not the life became intelligent is a different question, and we'll see if we find that.</p>
                <p class="fs-5 mb-4">If you get asteroids about a kilometer in size, those are large enough and carry enough energy into our system to disrupt transportation, communication, the food chains, and that can be a really bad day on Earth.</p>
                <h2 class="fw-bolder mb-4 mt-5">I have odd cosmic thoughts every day</h2>
                <p class="fs-5 mb-4">For me, the most fascinating interface is Twitter. I have odd cosmic thoughts every day and I realized I could hold them to myself or share them with people who might be interested.</p>
                <p class="fs-5 mb-4">Venus has a runaway greenhouse effect. I kind of want to know what happened there because we're twirling knobs here on Earth without knowing the consequences of it. Mars once had running water. It's bone dry today. Something bad happened there as well.</p>
            </section>
        </article>
        <!-- Comments section-->
        <section class="mb-5">
            <div class="card bg-light">
                <div class="card-body">
                    <!-- Comment form-->
                    <form class="mb-4"><textarea class="form-control" rows="3" placeholder="Join the discussion and leave a comment!"></textarea></form>
                    <!-- Comment with nested comments-->
                    <div class="d-flex mb-4">
                        <!-- Parent comment-->
                        <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                        <div class="ms-3">
                            <div class="fw-bold">Commenter Name</div>
                            If you're going to lead a space frontier, it has to be government; it'll never be private enterprise. Because the space frontier is dangerous, and it's expensive, and it has unquantified risks.
                            <!-- Child comment 1-->
                            <div class="d-flex mt-4">
                                <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                <div class="ms-3">
                                    <div class="fw-bold">Commenter Name</div>
                                    And under those conditions, you cannot establish a capital-market evaluation of that enterprise. You can't get investors.
                                </div>
                            </div>
                            <!-- Child comment 2-->
                            <div class="d-flex mt-4">
                                <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                <div class="ms-3">
                                    <div class="fw-bold">Commenter Name</div>
                                    When you put money directly to a problem, it makes a good headline.
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Single comment-->
                    <div class="d-flex">
                        <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                        <div class="ms-3">
                            <div class="fw-bold">Commenter Name</div>
                            When I look at the universe and all the ways the universe wants to kill us, I find it hard to reconcile that with statements of beneficence.
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <!-- Side widgets-->
    <div class="col-lg-4">
        <!-- Search widget-->
        <div class="card mb-4">
            <div class="card-header">Search</div>
            <div class="card-body">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                    <button class="btn btn-primary" id="button-search" type="button">Go!</button>
                </div>
            </div>
        </div>
        <!-- Categories widget-->
        <div class="card mb-4">
            <div class="card-header">Categories</div>
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-6">
                        <ul class="list-unstyled mb-0">
                            <li><a href="#!">Web Design</a></li>
                            <li><a href="#!">HTML</a></li>
                            <li><a href="#!">Freebies</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-6">
                        <ul class="list-unstyled mb-0">
                            <li><a href="#!">JavaScript</a></li>
                            <li><a href="#!">CSS</a></li>
                            <li><a href="#!">Tutorials</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- Side widget-->
        <div class="card mb-4">
            <div class="card-header">Side Widget</div>
            <div class="card-body">You can put anything you want inside of these side widgets. They are easy to use, and feature the Bootstrap 5 card component!</div>
        </div>
    </div>
</div>
</div>

templates/index.html
{% extends "layout.html" %}

{% block body %}

    <div class="jumbotron text-center">
        <h3>Django bloğu</h3>
        <p>Yeni bişeyler deniyoruz.</p>
    </div>

    <p>
        {% if request.user.is_authenticated %}
            Giriş Yapıldı, {{request.user.username}}
        
        {% else %}
            Giriş Yapılmadı
        {% endif %}
    </p>


{% endblock body %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Apo Blog</title>
</head>
<body>
    {% include "includes/navbar.html" %}
        <div style="margin-top :100px; margin-bottom:100px;" class="container">

            {% if messages %}
            {% for message in messages %}
                
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
            
            {% endif %}


            {% block body %}
            
            {% endblock body %}
        </div>

    
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/login.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">

        <h3>Giriş Yap</h3>
        <hr>

        <form method ="post">
            {% csrf_token %}
        
            {{ form|crispy }}
            <br>
            <button type="submit" class="btn btn-danger">Giriş Yap</button>
        </form>

    </div>
  </div>
{% endblock body %}

templates/register.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">

        <h3>Kayıt Ol</h3>
        <hr>

        <form method ="post">
            {% csrf_token %}
        
            {{ form|crispy }}
            <br>
            <button type="submit" class="btn btn-danger">Kayıt Ol</button>
        </form>

    </div>
  </div>

{% endblock body %}

templates/update.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">

        <h3>Makale Güncelle</h3>
        <hr>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{ form|crispy }}
            <br>
            <button type="submit" class="btn btn-danger">Güncelle</button>
            <a button type="submit" class="btn btn-danger" href="{{request.META.HTTP_REFERER}}">Geri Dön</a>
        </form>

    </div>
  </div>


{% endblock body %}